import type { Metadata } from "next";
import { Roboto, Roboto_Condensed } from "next/font/google";
import { clsx } from "clsx";
import "./globals.css";

const roboto = Roboto({
  variable: "--ff-roboto",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  variable: "--ff-roboto-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(roboto.variable, robotoCondensed.variable)}>
        {children}
      </body>
    </html>
  );
}
